import {
  Organization,
  Region,
  User,
  Project,
  ProjectUnit,
  Person,
  Lead,
  Activity,
  Task,
} from "@/types/crm";

export const INITIAL_ORG: Organization = {
  id: "org-dlf-partners",
  name: "Apex Realty Advisors",
  slug: "apex-realty",
};

export const INITIAL_REGIONS: Region[] = [
  { id: "reg-gurgaon", orgId: "org-dlf-partners", name: "Gurgaon", code: "GGN", activeLeadsCount: 142 },
  { id: "reg-noida", orgId: "org-dlf-partners", name: "Noida", code: "NDA", activeLeadsCount: 86 },
  { id: "reg-delhi", orgId: "org-dlf-partners", name: "Delhi", code: "DL", activeLeadsCount: 48 },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-vikram",
    orgId: "org-dlf-partners",
    name: "Vikram Malhotra",
    email: "vikram@apexrealty.in",
    phone: "+91 98111 00001",
    role: "boss",
    followUpCompletionRate: 98,
    avgResponseTimeHours: 0.5,
  },
  {
    id: "usr-rahul",
    orgId: "org-dlf-partners",
    name: "Rahul Sharma",
    email: "rahul@apexrealty.in",
    phone: "+91 98101 23456",
    role: "salesperson",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    followUpCompletionRate: 94,
    avgResponseTimeHours: 1.2,
  },
  {
    id: "usr-pooja",
    orgId: "org-dlf-partners",
    name: "Pooja Verma",
    email: "pooja@apexrealty.in",
    phone: "+91 98765 43210",
    role: "salesperson",
    regionId: "reg-noida",
    regionName: "Noida",
    followUpCompletionRate: 89,
    avgResponseTimeHours: 2.1,
  },
  {
    id: "usr-amit",
    orgId: "org-dlf-partners",
    name: "Amit Saxena",
    email: "amit@apexrealty.in",
    phone: "+91 98222 33445",
    role: "salesperson",
    regionId: "reg-delhi",
    regionName: "Delhi",
    followUpCompletionRate: 82,
    avgResponseTimeHours: 3.4,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-dlf-arbour",
    orgId: "org-dlf-partners",
    name: "DLF The Arbour",
    developer: "DLF Homes",
    location: "Sector 63, Golf Course Extension Rd",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    priceRange: "₹6.5 Cr - ₹8.5 Cr",
    status: "active",
    activeLeadsCount: 48,
    siteVisitsCount: 16,
    totalUnits: 120,
    availableUnitsCount: 38,
    bookedUnitsCount: 82,
    contacts: [
      { id: "pc-1", name: "Sanjay Kaul (Site Head)", role: "Developer RM", phone: "+91 99999 11223" },
    ],
  },
  {
    id: "proj-godrej-woods",
    orgId: "org-dlf-partners",
    name: "Godrej Woods",
    developer: "Godrej Properties",
    location: "Sector 43",
    regionId: "reg-noida",
    regionName: "Noida",
    priceRange: "₹2.4 Cr - ₹4.8 Cr",
    status: "active",
    activeLeadsCount: 36,
    siteVisitsCount: 12,
    totalUnits: 96,
    availableUnitsCount: 24,
    bookedUnitsCount: 72,
    contacts: [
      { id: "pc-2", name: "Rohit Mathur", role: "Sales RM", phone: "+91 98118 77665" },
    ],
  },
  {
    id: "proj-m3m-crown",
    orgId: "org-dlf-partners",
    name: "M3M Crown",
    developer: "M3M Group",
    location: "Sector 111, Dwarka Expressway",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    priceRange: "₹2.8 Cr - ₹5.2 Cr",
    status: "active",
    activeLeadsCount: 29,
    siteVisitsCount: 9,
    totalUnits: 140,
    availableUnitsCount: 52,
    bookedUnitsCount: 88,
  },
  {
    id: "proj-max-128",
    orgId: "org-dlf-partners",
    name: "Max Estates 128",
    developer: "Max Estates",
    location: "Noida Expressway, Sector 128",
    regionId: "reg-noida",
    regionName: "Noida",
    priceRange: "₹4.5 Cr - ₹9.0 Cr",
    status: "active",
    activeLeadsCount: 22,
    siteVisitsCount: 7,
    totalUnits: 80,
    availableUnitsCount: 18,
    bookedUnitsCount: 62,
  },
];

export const INITIAL_UNITS: ProjectUnit[] = [
  // DLF The Arbour Tower C
  {
    id: "unit-dlf-c1204",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    tower: "Tower C",
    unitNumber: "C-1204",
    floor: 12,
    configuration: "3 BHK + Servant",
    sizeSqFt: 1850,
    price: 65000000,
    status: "site_visit",
    assignedLeadId: "lead-101",
    assignedBuyerName: "Rajesh Singhal",
    facing: "Club & Green Facing",
  },
  {
    id: "unit-dlf-c1205",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    tower: "Tower C",
    unitNumber: "C-1205",
    floor: 12,
    configuration: "3 BHK + Servant",
    sizeSqFt: 1850,
    price: 64000000,
    status: "available",
    facing: "City Skyline",
  },
  {
    id: "unit-dlf-c1402",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    tower: "Tower C",
    unitNumber: "C-1402",
    floor: 14,
    configuration: "4 BHK Luxury",
    sizeSqFt: 2400,
    price: 81000000,
    status: "hold",
    assignedLeadId: "lead-105",
    assignedBuyerName: "Rohit Bansal",
    facing: "Aravalli Range View",
  },
  {
    id: "unit-dlf-c1501",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    tower: "Tower C",
    unitNumber: "C-1501",
    floor: 15,
    configuration: "4 BHK Penthouse",
    sizeSqFt: 3100,
    price: 98000000,
    status: "available",
    facing: "Panoramic Dual Balcony",
  },
  {
    id: "unit-dlf-b0802",
    orgId: "org-dlf-partners",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    tower: "Tower B",
    unitNumber: "B-0802",
    floor: 8,
    configuration: "3 BHK",
    sizeSqFt: 1750,
    price: 61000000,
    status: "sold",
    facing: "Internal Garden",
  },

  // Godrej Woods Tower A
  {
    id: "unit-gw-a1402",
    orgId: "org-dlf-partners",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    tower: "Tower A",
    unitNumber: "A-1402",
    floor: 14,
    configuration: "3 BHK + Study",
    sizeSqFt: 1550,
    price: 28500000,
    status: "negotiation",
    assignedLeadId: "lead-102",
    assignedBuyerName: "Ananya Deshmukh",
    facing: "Forest Trail Facing",
  },
  {
    id: "unit-gw-a1403",
    orgId: "org-dlf-partners",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    tower: "Tower A",
    unitNumber: "A-1403",
    floor: 14,
    configuration: "2 BHK Executive",
    sizeSqFt: 1150,
    price: 22000000,
    status: "available",
    facing: "Clubhouse View",
  },
  {
    id: "unit-gw-b0901",
    orgId: "org-dlf-partners",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    tower: "Tower B",
    unitNumber: "B-0901",
    floor: 9,
    configuration: "3 BHK",
    sizeSqFt: 1450,
    price: 26500000,
    status: "available",
    facing: "Green Corridor",
  },

  // M3M Crown Tower D
  {
    id: "unit-m3m-d0604",
    orgId: "org-dlf-partners",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    tower: "Tower D",
    unitNumber: "D-0604",
    floor: 6,
    configuration: "3 BHK + Servant",
    sizeSqFt: 1950,
    price: 34000000,
    status: "hold",
    assignedLeadId: "lead-103",
    assignedBuyerName: "Vikram Mehra",
    facing: "North-East / Express Highway",
  },
  {
    id: "unit-m3m-d0801",
    orgId: "org-dlf-partners",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    tower: "Tower D",
    unitNumber: "D-0801",
    floor: 8,
    configuration: "3 BHK",
    sizeSqFt: 1700,
    price: 31000000,
    status: "site_visit",
    assignedLeadId: "lead-106",
    assignedBuyerName: "Kavita Sethi",
    facing: "Central Lagoon",
  },

  // Max 128
  {
    id: "unit-max-1804",
    orgId: "org-dlf-partners",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    tower: "Tower 1",
    unitNumber: "T1-1804",
    floor: 18,
    configuration: "4 BHK Signature",
    sizeSqFt: 2800,
    price: 52000000,
    status: "booked",
    assignedLeadId: "lead-104",
    assignedBuyerName: "Suresh Gupta",
    facing: "Expressway & Golf Greens",
  },
];

export const INITIAL_PEOPLE: Person[] = [
  {
    id: "per-1",
    orgId: "org-dlf-partners",
    name: "Rajesh Singhal",
    phone: "+91 98112 34567",
    email: "rajesh.singhal@rediffmail.com",
    city: "Gurgaon",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    preferredConfiguration: "4 BHK Luxury",
    budget: 65000000,
    createdAt: "2026-08-14T09:00:00Z",
  },
  {
    id: "per-2",
    orgId: "org-dlf-partners",
    name: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    email: "ananya.d@fintech.co",
    city: "Noida",
    regionId: "reg-noida",
    regionName: "Noida",
    preferredConfiguration: "3 BHK + Study",
    budget: 28500000,
    createdAt: "2026-08-10T11:15:00Z",
  },
  {
    id: "per-3",
    orgId: "org-dlf-partners",
    name: "Vikram Mehra",
    phone: "+91 99887 76655",
    email: "vmehra@autocorp.in",
    city: "Gurgaon",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    preferredConfiguration: "3 BHK + Servant",
    budget: 34000000,
    createdAt: "2026-08-15T15:40:00Z",
  },
  {
    id: "per-4",
    orgId: "org-dlf-partners",
    name: "Suresh Gupta",
    phone: "+91 98100 98100",
    email: "suresh.gupta@textiles.com",
    city: "Delhi",
    regionId: "reg-noida",
    regionName: "Noida",
    preferredConfiguration: "4 BHK Signature",
    budget: 52000000,
    createdAt: "2026-07-28T12:00:00Z",
  },
  {
    id: "per-5",
    orgId: "org-dlf-partners",
    name: "Rohit Bansal",
    phone: "+91 98105 55667",
    email: "rohit.b@dubaiholding.ae",
    city: "Dubai (NRI)",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    preferredConfiguration: "4 BHK High Floor",
    budget: 70000000,
    createdAt: "2026-08-20T08:15:00Z",
  },
  {
    id: "per-6",
    orgId: "org-dlf-partners",
    name: "Kavita Sethi",
    phone: "+91 98188 12345",
    email: "kavita.sethi@gmail.com",
    city: "Gurgaon",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    preferredConfiguration: "3 BHK Central View",
    budget: 31000000,
    createdAt: "2026-08-19T09:30:00Z",
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-101",
    orgId: "org-dlf-partners",
    personId: "per-1",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    email: "rajesh.singhal@rediffmail.com",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 65000000,
    stage: "site_visit",
    source: "Google Search Ad",
    leadScore: 94,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthReason: "Family visit confirmed, pre-approved ₹5.5 Cr loan",
    recommendedAction: "Arrange golf cart at Site Office & introduce Project Head",
    configurationPreference: "4 BHK Luxury",
    preferredFloor: "12th to 16th (High Floor)",
    facingPreference: "Club & Green Facing",
    parkingRequirement: "2 Covered Stacks",
    buyerIntent: "End-User (Upgrading from Sector 54)",
    decisionMakers: "Self & Brother",
    buyingSignals: [
      "Budget verified (HDFC Pre-approved)",
      "Unit C-1204 shortlisted",
      "Family involved in visit",
      "Site visit confirmed",
    ],
    objections: ["Price negotiation on PLC", "Possession timeline clarity"],
    lastConversationSummary:
      "Customer confirmed for Sunday 11 AM with brother. Prefers Tower C high floor, looking for green-facing balcony. Ready to issue token if floor rise is adjusted.",
    suggestedNextMove:
      "Arrange site office golf cart reception and present Tower C vs D comparative inventory sheet.",
    assignedUnitId: "unit-dlf-c1204",
    assignedUnitNumber: "C-1204",
    daysInStage: 2,
    lastActivityText: "Call: Confirmed site visit for Sunday 11:00 AM with family",
    lastActivityAt: "2026-08-20T10:30:00Z",
    nextFollowUpAt: "Today, 11:00 AM",
    followUpStatus: "due_today",
    notes: "Requires 4 BHK with 2 car parkings, high floor preferred.",
    createdAt: "2026-08-14T09:00:00Z",
  },
  {
    id: "lead-102",
    orgId: "org-dlf-partners",
    personId: "per-2",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    email: "ananya.d@fintech.co",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    regionId: "reg-noida",
    regionName: "Noida",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    budget: 28500000,
    stage: "negotiation",
    source: "99acres Direct",
    leadScore: 88,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthReason: "Floor rise waiver under review by developer",
    recommendedAction: "Close negotiation with 1.5% token incentive this weekend",
    configurationPreference: "3 BHK + Study",
    preferredFloor: "10th - 15th",
    facingPreference: "Central Forest View",
    parkingRequirement: "1 Covered Car Park",
    buyerIntent: "End-User (First-time Luxury Buyer)",
    decisionMakers: "Buyer & Spouse",
    buyingSignals: [
      "Budget verified",
      "Unit A-1402 shortlisted",
      "Payment plan discussed (20:80)",
      "Negotiation started",
    ],
    objections: ["Floor rise surcharge", "Bank subvention eligibility"],
    lastConversationSummary:
      "Discussed payment plan 20:80 and floor rise discount. Client is comfortable with ₹2.85 Cr all-inclusive.",
    suggestedNextMove:
      "Send final sanction sheet with 1.5% builder festive incentive.",
    assignedUnitId: "unit-gw-a1402",
    assignedUnitNumber: "A-1402",
    daysInStage: 4,
    lastActivityText: "WhatsApp: Shared unit layout #1402 and payment schedule",
    lastActivityAt: "2026-08-19T16:20:00Z",
    nextFollowUpAt: "Tomorrow, 2:30 PM",
    followUpStatus: "upcoming",
    notes: "Evaluating bank loan with HDFC vs ICICI. Final negotiation on floor rise.",
    createdAt: "2026-08-10T11:15:00Z",
  },
  {
    id: "lead-103",
    orgId: "org-dlf-partners",
    personId: "per-3",
    personName: "Vikram Mehra",
    phone: "+91 99887 76655",
    email: "vmehra@autocorp.in",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 34000000,
    stage: "qualified",
    source: "Referral (Dr. Bhatia)",
    leadScore: 91,
    leadScoreLabel: "Hot",
    dealHealth: "at_risk",
    dealHealthReason: "No activity for 4 days · Follow-up overdue",
    recommendedAction: "Send Tower C vs D floor-plan comparison and call today",
    configurationPreference: "3 BHK + Servant",
    preferredFloor: "6th - 10th",
    facingPreference: "North-East Facing",
    parkingRequirement: "2 Covered Parkings",
    buyerIntent: "Primary Residence (Proximity to IGI Airport)",
    decisionMakers: "Self (VP at Auto Corp)",
    buyingSignals: [
      "Budget verified (₹3.4 Cr)",
      "Unit D-0604 held tentatively",
      "Dwarka Expressway connectivity verified",
    ],
    objections: ["Price comparison with Smartworld One DXP", "Maintenance charges"],
    lastConversationSummary:
      "Client is comparing M3M Crown with nearby developments. Likes the 3BHK + servant layout in Tower D. Wants clarification on payment milestones.",
    suggestedNextMove:
      "Call immediately with Tower D floor plan and milestone payment breakdown.",
    assignedUnitId: "unit-m3m-d0604",
    assignedUnitNumber: "D-0604",
    daysInStage: 6,
    lastActivityText: "Call: Budget confirmed at ₹3.4 Cr, looking for 3 BHK + Servant",
    lastActivityAt: "2026-08-16T14:10:00Z",
    nextFollowUpAt: "Yesterday (Overdue)",
    followUpStatus: "overdue",
    notes: "Needs Dwarka Expressway connectivity to IGI Airport.",
    createdAt: "2026-08-15T15:40:00Z",
  },
  {
    id: "lead-104",
    orgId: "org-dlf-partners",
    personId: "per-4",
    personName: "Suresh Gupta",
    phone: "+91 98100 98100",
    email: "suresh.gupta@textiles.com",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    regionId: "reg-noida",
    regionName: "Noida",
    salespersonId: "usr-amit",
    salespersonName: "Amit Saxena",
    budget: 52000000,
    stage: "won",
    source: "Direct Walk-in",
    leadScore: 99,
    leadScoreLabel: "Hot",
    dealHealth: "strong",
    dealHealthReason: "Booking token cleared; Agreement registered",
    recommendedAction: "Submit brokerage invoice to Max Estates finance",
    configurationPreference: "4 BHK Signature",
    preferredFloor: "18th (Top Floor Luxury)",
    facingPreference: "Golf Greens Facing",
    parkingRequirement: "3 Covered Parkings",
    buyerIntent: "Luxury Living / Portfolio Expansion",
    decisionMakers: "Family Trust",
    buyingSignals: [
      "Budget verified",
      "Unit T1-1804 booked",
      "Token cheque cleared",
      "Agreement registered",
    ],
    objections: [],
    lastConversationSummary:
      "₹5.2 Cr booking token received. Application filed and allotment letter issued by Max Estates.",
    suggestedNextMove:
      "Dispatch client onboarding gift hamper and follow up on registration stamp duty.",
    assignedUnitId: "unit-max-1804",
    assignedUnitNumber: "T1-1804",
    daysInStage: 1,
    lastActivityText: "Deal Won: ₹5.2 Cr booking token received. Application filed.",
    lastActivityAt: "2026-08-17T18:00:00Z",
    nextFollowUpAt: "Completed",
    followUpStatus: "completed",
    notes: "Unit 1804 booked. Commission invoice submitted to developer.",
    createdAt: "2026-07-28T12:00:00Z",
  },
  {
    id: "lead-105",
    orgId: "org-dlf-partners",
    personId: "per-5",
    personName: "Rohit Bansal",
    phone: "+91 98105 55667",
    email: "rohit.b@dubaiholding.ae",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 70000000,
    stage: "new",
    source: "Facebook Campaign",
    leadScore: 78,
    leadScoreLabel: "Warm",
    dealHealth: "neutral",
    dealHealthReason: "Fresh inquiry (under 24 hours), awaiting video walk-through",
    recommendedAction: "Send WhatsApp high-res project video & schedule Zoom call",
    configurationPreference: "4 BHK Luxury High Floor",
    preferredFloor: "14th or above",
    facingPreference: "City Skyline",
    parkingRequirement: "2 Covered Parkings",
    buyerIntent: "NRI Investment (Dubai Resident)",
    decisionMakers: "Self",
    buyingSignals: [
      "High budget capability (₹7.0 Cr)",
      "High-intent inquiry from Dubai",
      "Unit C-1402 option presented",
    ],
    objections: ["Remote booking process & POA documentation"],
    lastConversationSummary:
      "Inquired via NRI campaign. Looking for premium 4BHK with immediate capital appreciation potential on Golf Course Extension Road.",
    suggestedNextMove:
      "Conduct 15-min virtual walkthrough and explain NRI FEMA remittance process.",
    assignedUnitId: "unit-dlf-c1402",
    assignedUnitNumber: "C-1402",
    daysInStage: 1,
    lastActivityText: "Lead created from Meta Campaign",
    lastActivityAt: "2026-08-20T08:15:00Z",
    nextFollowUpAt: "Today, 4:00 PM",
    followUpStatus: "due_today",
    notes: "NRI buyer located in Dubai, looking for investment on GCE Rd.",
    createdAt: "2026-08-20T08:15:00Z",
  },
  {
    id: "lead-106",
    orgId: "org-dlf-partners",
    personId: "per-6",
    personName: "Kavita Sethi",
    phone: "+91 98188 12345",
    email: "kavita.sethi@gmail.com",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 31000000,
    stage: "contacted",
    source: "MagicBricks",
    leadScore: 82,
    leadScoreLabel: "Warm",
    dealHealth: "neutral",
    dealHealthReason: "Brochure shared; pending site visit appointment",
    recommendedAction: "Call to confirm Saturday morning site visit slot",
    configurationPreference: "3 BHK Central View",
    preferredFloor: "8th Floor",
    facingPreference: "Central Lagoon",
    parkingRequirement: "1 Covered Car Park",
    buyerIntent: "End-User (Family Relocation)",
    decisionMakers: "Buyer & Parents",
    buyingSignals: ["Brochure downloaded", "Unit D-0801 viewed on portal"],
    objections: ["Kitchen appliance fitments", "Clubhouse completion date"],
    lastConversationSummary:
      "Connected briefly on WhatsApp. Requested floor plan for Unit D-0801. Interested in viewing on Saturday.",
    suggestedNextMove:
      "Send WhatsApp invitation with location pin for Saturday 11:30 AM site visit.",
    assignedUnitId: "unit-m3m-d0801",
    assignedUnitNumber: "D-0801",
    daysInStage: 2,
    lastActivityText: "Call: Connected briefly, requested brochure via WhatsApp",
    lastActivityAt: "2026-08-19T11:45:00Z",
    nextFollowUpAt: "Tomorrow, 11:30 AM",
    followUpStatus: "upcoming",
    notes: "Checking if modular kitchen included in standard package.",
    createdAt: "2026-08-19T09:30:00Z",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "tsk-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Confirm Site Visit & Pick-up arrangement with brother",
    dueDate: "Today",
    dueTime: "11:00 AM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-2",
    orgId: "org-dlf-partners",
    leadId: "lead-105",
    personName: "Rohit Bansal (NRI)",
    phone: "+91 98105 55667",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "First qualifying call & WhatsApp project video walkthrough",
    dueDate: "Today",
    dueTime: "4:00 PM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-3",
    orgId: "org-dlf-partners",
    leadId: "lead-103",
    personName: "Vikram Mehra",
    phone: "+91 99887 76655",
    projectName: "M3M Crown",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Send floor plan comparison for Tower C vs D (Overdue 4 days)",
    dueDate: "Yesterday",
    status: "overdue",
    priority: "high",
  },
  {
    id: "tsk-4",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    projectName: "Godrej Woods",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    title: "Follow up on HDFC home loan pre-approval & floor rise sanction",
    dueDate: "Tomorrow",
    dueTime: "2:30 PM",
    status: "upcoming",
    priority: "medium",
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    personName: "Rajesh Singhal",
    userId: "usr-rahul",
    userName: "Rahul Sharma",
    type: "call",
    outcome: "site_visit_booked",
    outcomeLabel: "Site Visit Booked",
    notes: "Customer confirmed for Sunday 11 AM at DLF Site Office with his brother.",
    scheduledFollowUpAt: "Today, 11:00 AM",
    createdAt: "2026-08-20T10:30:00Z",
  },
  {
    id: "act-2",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    personName: "Ananya Deshmukh",
    userId: "usr-pooja",
    userName: "Pooja Verma",
    type: "whatsapp",
    notes: "Shared payment schedule 20:80 and floor plan layout for unit #A-1402.",
    createdAt: "2026-08-19T16:20:00Z",
  },
  {
    id: "act-3",
    orgId: "org-dlf-partners",
    leadId: "lead-103",
    personName: "Vikram Mehra",
    userId: "usr-rahul",
    userName: "Rahul Sharma",
    type: "call",
    outcome: "interested",
    outcomeLabel: "Interested",
    notes: "Budget verified at ₹3.4 Cr. Specific requirement: North-East facing balcony.",
    createdAt: "2026-08-16T14:10:00Z",
  },
  {
    id: "act-4",
    orgId: "org-dlf-partners",
    leadId: "lead-104",
    personName: "Suresh Gupta",
    userId: "usr-amit",
    userName: "Amit Saxena",
    type: "booking",
    outcome: "interested",
    outcomeLabel: "Booking Token Received",
    notes: "Cheque handed over for Max 128 Unit T1-1804. KYC documents collected.",
    createdAt: "2026-08-17T18:00:00Z",
  },
];

