import {
  Organization,
  Region,
  User,
  Project,
  Person,
  Lead,
  Activity,
  Task,
} from "@/types/crm";

export const INITIAL_ORG: Organization = {
  id: "org-dlf-partners",
  name: "Apex Realty Advisors",
  slug: "apex-realty",
};

export const INITIAL_REGIONS: Region[] = [
  { id: "reg-gurgaon", orgId: "org-dlf-partners", name: "Gurgaon", code: "GGN", activeLeadsCount: 142 },
  { id: "reg-noida", orgId: "org-dlf-partners", name: "Noida", code: "NDA", activeLeadsCount: 86 },
  { id: "reg-delhi", orgId: "org-dlf-partners", name: "Delhi", code: "DL", activeLeadsCount: 48 },
];

export const INITIAL_USERS: User[] = [
  {
    id: "usr-vikram",
    orgId: "org-dlf-partners",
    name: "Vikram Malhotra",
    email: "vikram@apexrealty.in",
    phone: "+91 98111 00001",
    role: "boss",
  },
  {
    id: "usr-rahul",
    orgId: "org-dlf-partners",
    name: "Rahul Sharma",
    email: "rahul@apexrealty.in",
    phone: "+91 98101 23456",
    role: "salesperson",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
  },
  {
    id: "usr-pooja",
    orgId: "org-dlf-partners",
    name: "Pooja Verma",
    email: "pooja@apexrealty.in",
    phone: "+91 98765 43210",
    role: "salesperson",
    regionId: "reg-noida",
    regionName: "Noida",
  },
  {
    id: "usr-amit",
    orgId: "org-dlf-partners",
    name: "Amit Saxena",
    email: "amit@apexrealty.in",
    phone: "+91 98222 33445",
    role: "salesperson",
    regionId: "reg-delhi",
    regionName: "Delhi",
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj-dlf-arbour",
    orgId: "org-dlf-partners",
    name: "DLF The Arbour",
    developer: "DLF Homes",
    location: "Sector 63, Golf Course Extension Rd",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    priceRange: "₹6.5 Cr - ₹8.5 Cr",
    status: "active",
    activeLeadsCount: 48,
    siteVisitsCount: 16,
    contacts: [
      { id: "pc-1", name: "Sanjay Kaul (Site Head)", role: "Developer RM", phone: "+91 99999 11223" },
    ],
  },
  {
    id: "proj-godrej-woods",
    orgId: "org-dlf-partners",
    name: "Godrej Woods",
    developer: "Godrej Properties",
    location: "Sector 43",
    regionId: "reg-noida",
    regionName: "Noida",
    priceRange: "₹2.4 Cr - ₹4.8 Cr",
    status: "active",
    activeLeadsCount: 36,
    siteVisitsCount: 12,
  },
  {
    id: "proj-m3m-crown",
    orgId: "org-dlf-partners",
    name: "M3M Crown",
    developer: "M3M Group",
    location: "Sector 111, Dwarka Expressway",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    priceRange: "₹2.8 Cr - ₹5.2 Cr",
    status: "active",
    activeLeadsCount: 29,
    siteVisitsCount: 9,
  },
  {
    id: "proj-max-128",
    orgId: "org-dlf-partners",
    name: "Max Estates 128",
    developer: "Max Estates",
    location: "Noida Expressway, Sector 128",
    regionId: "reg-noida",
    regionName: "Noida",
    priceRange: "₹4.5 Cr - ₹9.0 Cr",
    status: "active",
    activeLeadsCount: 22,
    siteVisitsCount: 7,
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-101",
    orgId: "org-dlf-partners",
    personId: "per-1",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    email: "rajesh.singhal@rediffmail.com",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 65000000,
    stage: "site_visit",
    source: "Google Search Ad",
    lastActivityText: "Call: Confirmed site visit for Sunday 11:00 AM with family",
    lastActivityAt: "2026-08-20T10:30:00Z",
    nextFollowUpAt: "Today, 11:00 AM",
    followUpStatus: "due_today",
    notes: "Requires 4 BHK with 2 car parkings, high floor preferred.",
    createdAt: "2026-08-14T09:00:00Z",
  },
  {
    id: "lead-102",
    orgId: "org-dlf-partners",
    personId: "per-2",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    email: "ananya.d@fintech.co",
    projectId: "proj-godrej-woods",
    projectName: "Godrej Woods",
    regionId: "reg-noida",
    regionName: "Noida",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    budget: 28500000,
    stage: "negotiation",
    source: "99acres Direct",
    lastActivityText: "WhatsApp: Shared unit layout #1402 and construction update",
    lastActivityAt: "2026-08-19T16:20:00Z",
    nextFollowUpAt: "Tomorrow, 2:30 PM",
    followUpStatus: "upcoming",
    notes: "Evaluating bank loan with HDFC vs ICICI. Final negotiation on floor rise.",
    createdAt: "2026-08-10T11:15:00Z",
  },
  {
    id: "lead-103",
    orgId: "org-dlf-partners",
    personId: "per-3",
    personName: "Vikram Mehra",
    phone: "+91 99887 76655",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 34000000,
    stage: "qualified",
    source: "Referral (Dr. Bhatia)",
    lastActivityText: "Call: Budget confirmed at ₹3.4 Cr, looking for 3 BHK + Servant",
    lastActivityAt: "2026-08-18T14:10:00Z",
    nextFollowUpAt: "Yesterday",
    followUpStatus: "overdue",
    notes: "Needs Dwarka Expressway connectivity to IGI Airport.",
    createdAt: "2026-08-15T15:40:00Z",
  },
  {
    id: "lead-104",
    orgId: "org-dlf-partners",
    personId: "per-4",
    personName: "Suresh Gupta",
    phone: "+91 98100 98100",
    projectId: "proj-max-128",
    projectName: "Max Estates 128",
    regionId: "reg-noida",
    regionName: "Noida",
    salespersonId: "usr-amit",
    salespersonName: "Amit Saxena",
    budget: 52000000,
    stage: "won",
    source: "Direct Walk-in",
    lastActivityText: "Deal Won: ₹5.2 Cr booking token received. Application filed.",
    lastActivityAt: "2026-08-17T18:00:00Z",
    nextFollowUpAt: "Completed",
    followUpStatus: "completed",
    notes: "Unit 1804 booked. Commission invoice submitted to developer.",
    createdAt: "2026-07-28T12:00:00Z",
  },
  {
    id: "lead-105",
    orgId: "org-dlf-partners",
    personId: "per-5",
    personName: "Rohit Bansal",
    phone: "+91 98105 55667",
    projectId: "proj-dlf-arbour",
    projectName: "DLF The Arbour",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 70000000,
    stage: "new",
    source: "Facebook Campaign",
    lastActivityText: "Lead created from Meta Campaign",
    lastActivityAt: "2026-08-20T08:15:00Z",
    nextFollowUpAt: "Today, 4:00 PM",
    followUpStatus: "due_today",
    notes: "NRI buyer located in Dubai, looking for investment on GCE Rd.",
    createdAt: "2026-08-20T08:15:00Z",
  },
  {
    id: "lead-106",
    orgId: "org-dlf-partners",
    personId: "per-6",
    personName: "Kavita Sethi",
    phone: "+91 98188 12345",
    projectId: "proj-m3m-crown",
    projectName: "M3M Crown",
    regionId: "reg-gurgaon",
    regionName: "Gurgaon",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    budget: 31000000,
    stage: "contacted",
    source: "MagicBricks",
    lastActivityText: "Call: Connected briefly, requested brochure via WhatsApp",
    lastActivityAt: "2026-08-19T11:45:00Z",
    nextFollowUpAt: "Tomorrow, 11:30 AM",
    followUpStatus: "upcoming",
    notes: "Checking if modular kitchen included in standard package.",
    createdAt: "2026-08-19T09:30:00Z",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "tsk-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    personName: "Rajesh Singhal",
    phone: "+91 98112 34567",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Confirm Site Visit & Pick up arrangement",
    dueDate: "Today",
    dueTime: "11:00 AM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-2",
    orgId: "org-dlf-partners",
    leadId: "lead-105",
    personName: "Rohit Bansal (NRI)",
    phone: "+91 98105 55667",
    projectName: "DLF The Arbour",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "First qualifying call & WhatsApp project video",
    dueDate: "Today",
    dueTime: "4:00 PM",
    status: "due_today",
    priority: "high",
  },
  {
    id: "tsk-3",
    orgId: "org-dlf-partners",
    leadId: "lead-103",
    personName: "Vikram Mehra",
    phone: "+91 99887 76655",
    projectName: "M3M Crown",
    salespersonId: "usr-rahul",
    salespersonName: "Rahul Sharma",
    title: "Overdue: Send floor plan comparison for Tower C vs D",
    dueDate: "Yesterday",
    status: "overdue",
    priority: "high",
  },
  {
    id: "tsk-4",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    personName: "Ananya Deshmukh",
    phone: "+91 98765 43210",
    projectName: "Godrej Woods",
    salespersonId: "usr-pooja",
    salespersonName: "Pooja Verma",
    title: "Follow up on HDFC home loan pre-approval",
    dueDate: "Tomorrow",
    dueTime: "2:30 PM",
    status: "upcoming",
    priority: "medium",
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    orgId: "org-dlf-partners",
    leadId: "lead-101",
    personName: "Rajesh Singhal",
    userId: "usr-rahul",
    userName: "Rahul Sharma",
    type: "call",
    outcome: "site_visit_booked",
    outcomeLabel: "Site Visit Booked",
    notes: "Customer confirmed for Sunday 11 AM at DLF Site Office with his brother.",
    scheduledFollowUpAt: "2026-08-24T11:00:00Z",
    createdAt: "2026-08-20T10:30:00Z",
  },
  {
    id: "act-2",
    orgId: "org-dlf-partners",
    leadId: "lead-102",
    personName: "Ananya Deshmukh",
    userId: "usr-pooja",
    userName: "Pooja Verma",
    type: "whatsapp",
    notes: "Shared payment schedule 20:80 and floor plan layout for unit #1402.",
    createdAt: "2026-08-19T16:20:00Z",
  },
  {
    id: "act-3",
    orgId: "org-dlf-partners",
    leadId: "lead-103",
    personName: "Vikram Mehra",
    userId: "usr-rahul",
    userName: "Rahul Sharma",
    type: "call",
    outcome: "interested",
    outcomeLabel: "Interested",
    notes: "Budget verified at ₹3.4 Cr. Specific requirement: North-East facing balcony.",
    createdAt: "2026-08-18T14:10:00Z",
  },
  {
    id: "act-4",
    orgId: "org-dlf-partners",
    leadId: "lead-104",
    personName: "Suresh Gupta",
    userId: "usr-amit",
    userName: "Amit Saxena",
    type: "meeting",
    outcome: "interested",
    outcomeLabel: "Booking Token Received",
    notes: "Cheque handed over for Max 128 Unit 1804. KYC documents collected.",
    createdAt: "2026-08-17T18:00:00Z",
  },
];
